DOMAIN = "tecomat_foxtrot"
CONF_HOST = "host"
CONF_PORT = "port"
DEFAULT_PORT = 5010

PLATFORMS = ["sensor", "binary_sensor", "switch", "light", "cover", "climate"]

SENSOR_DISPLAY_TYPE_REAL = 1
SENSOR_DISPLAY_SYMBOL_GENERIC = 0
SENSOR_DISPLAY_SYMBOL_TEMP = 100
SENSOR_DISPLAY_SYMBOL_HUMIDITY = 101
SENSOR_DISPLAY_SYMBOL_LUX = 107
SENSOR_DISPLAY_SYMBOL_CO2 = 104
SENSOR_DISPLAY_SYMBOL_CO = 105

DISP = "GTSAP1_DISPLAY"
CONTACT_BASE = "GTSAP1_CONTACT"
SOCKET_BASE = "GTSAP1_SOCKET"
LIGHT_BASE = "GTSAP1_LIGHT"
COVER_BASE = "GTSAP1_OPENER"
THERMOSTAT_BASE = "GTSAP1_THERMOSTAT"
BUTTON_BASE = "GTSAP1_BUTTON"

SUBSCRIBE_WILDCARD = "EN:*"

ENCODING = "cp1250"

RECONNECT_MIN_DELAY = 2
RECONNECT_MAX_DELAY = 30